# Default values for five-g-appl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: accelleran/e2smkpmappl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: accelleran-secret
nameOverride: ""
fullnameOverride: ""

# Application Settings
# cmd: "__APPNAME=amfController ./amfControllerAppl.exe"
cmd: "./e2SmKpmAppl.exe"

args: []
#  - name: "--own"
#    value: 127.0.0.1
#  - name: "--ng"
#    value: 127.0.0.5

nats:
  url: "10.55.1.2"
  port: "31100"

redisConfig:
  hostname: "10.55.1.2"
  port: "32200"

bootstrapId: "e2-t"
bootstrapFile: /bootstrap.txt

jaegerAgentHost: "ric-jaeger-agent"

extraEnvs:
  - name: __APPNAME
    value: e2SmKpm
#  - name: ex1
#    value: ex1

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 0
  privileged: true

service:
  enabled: false
  name: "e2-sm-kpm"
  type: NodePort
  protocol: SCTP
  port: 80
  # loadBalancerIP:
  # nodePort:
  # externalTrafficPolicy: "Local"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

draxNodeSelectorEnabled: "false"

draxNodeSelector:
  draxName: "main"

tolerations: []

affinity: {}

developerMode:
  enabled: false
  hostPath: ""