global:
  # Number of supported components
  #   Description:  You have to specify the amount of different components that should be supported.
  #                 Therefore, you have to specify:
  #
  numOfE2Nodes: 5

  # Bootstrap Instance ID
  #   Description:  The Bootstrap Instance ID. Is used by the logical group:
  #                 SCTP and all APs associated to that SCTP module.
  #
  #   Example:
  # bootstrapId: "e2-t"
  #
  bootstrapId: "e2-t"

  # NATS URL and PORT
  #   Description: Used to configure the application to talk
  #                to NATS
  #   Value type: string
  #
  natsUrl: "10.55.1.2"
  natsPort: "31100"


  # Version of the 5G applications
  #   Description: This is the version of the 5G applications
  #                in DockerHub.
  #   Value type: string
  #
  tag: "master-8341e9f4"


  # Redis settings
  #   Description: Certain application need to be able to reach
  #                Redis. Here we configure the Redis hostname
  #                and port.
  #   Value type: string
  #   Example:
  #
  redisHostname: "10.55.1.2"
  redisPort: "32200"


  # dRAX Specific Node Selector
  #   Description: This is a special nodeSelector field implemented for the
  #                Accelleran 5G Helm charts. You need to first label your
  #                node in Kubernetes with a label "draxName" and give it a
  #                <value>. For example for node <node_name>, you can use the
  #                following command to label it:
  #                kubectl label node <node_name> draxName=<value>.
  #                You can then enabled this feature by setting
  #                "draxNodeSelectorEnabled" to "true" (as a string with quotes!).
  #                The in "draxName" set the value of the label you chose for
  #                the node. This will in effect install all the 5G Application
  #                on that node, without the need to edit all individual helm
  #                charts. In case you want to add other nodeSelector options,
  #                you have to add them to the helm chart specific values files.
  #   Value type: string
  #   Example:
  #
  draxNodeSelectorEnabled: "false"
  draxName: "main"

  # Jaeger settings
  #   Description:  Sets the DNS hostname where the Jaeger agent is located
  #   Value type:   string
  #   Example: jaegerAgentHost: "ric-jaeger-agent"
  jaegerAgentHost: "ric-jaeger-agent"

e2t-sctp:
  enabled: true

  image:
    tag: "{{ .Values.global.tag }}"

  redisConfig:
    hostname: "{{ .Values.global.redisHostname }}"
    port: "{{ .Values.global.redisPort }}"

  nats:
    url: "{{ .Values.global.natsUrl }}"
    port: "{{ .Values.global.natsPort }}"

  bootstrapId: "{{ .Values.global.bootstrapId }}"

  jaegerAgentHost: "{{ .Values.global.jaegerAgentHost }}"

  sctpService:
    nodePort: 31900

  draxNodeSelectorEnabled: "{{ .Values.global.draxNodeSelectorEnabled }}"
  draxNodeSelector:
    draxName: "{{ .Values.global.draxName }}"

  ### TODO REMOVE
  developerMode:
    enabled: false
    hostPath: ""

e2t-ap:
  enabled: true

  numOfE2Nodes: "{{ .Values.global.numOfE2Nodes }}"

  image:
    tag: "{{ .Values.global.tag }}"

  redisConfig:
    hostname: "{{ .Values.global.redisHostname }}"
    port: "{{ .Values.global.redisPort }}"

  nats:
    url: "{{ .Values.global.natsUrl }}"
    port: "{{ .Values.global.natsPort }}"

  bootstrapId: "{{ .Values.global.bootstrapId }}"

  jaegerAgentHost: "{{ .Values.global.jaegerAgentHost }}"

  draxNodeSelectorEnabled: "{{ .Values.global.draxNodeSelectorEnabled }}"
  draxNodeSelector:
    draxName: "{{ .Values.global.draxName }}"

  ### TODO REMOVE
  developerMode:
    enabled: false
    hostPath: ""
