apiVersion: v1
kind: ConfigMap
metadata:
 name: prov-dhcp-conf
 labels:
   {{- include "provisioner-dhcp.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "udhcpd.conf" }}
  {{ . }}:
    {{ $files.Get . | quote }}
  {{- end }}
