apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.serviceName . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.service.client.name }}
      {{ if .Values.service.client.nodePort }}
      nodePort: {{ .Values.service.client.nodePort }}
      {{ end }}
      port: {{ .Values.service.client.port }}
      protocol: TCP
    - name: {{ .Values.service.cluster.name }}
      {{ if .Values.service.cluster.nodePort }}
      nodePort: {{ .Values.service.cluster.nodePort }}
      {{ end }}
      port: {{ .Values.service.cluster.port }}
      protocol: TCP
    - name: {{ .Values.service.monitoring.name }}
      {{ if .Values.service.monitoring.nodePort }}
      nodePort: {{ .Values.service.monitoring.nodePort }}
      {{ end }}
      port: {{ .Values.service.monitoring.port }}
      protocol: TCP
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
