apiVersion: v1
kind: Service
metadata:
  name: nats-service
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.service.client.name }}
      nodePort: {{ .Values.service.client.nodePort }}
      port: {{ .Values.service.client.port }}
      protocol: TCP
    - name: {{ .Values.service.cluster.name }}
      nodePort: {{ .Values.service.cluster.nodePort }}
      port: {{ .Values.service.cluster.port }}
      protocol: TCP
    - name: {{ .Values.service.monitoring.name }}
      nodePort: {{ .Values.service.monitoring.nodePort }}
      port: {{ .Values.service.monitoring.port }}
      protocol: TCP
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
