apiVersion: v1
kind: ConfigMap
metadata:
 name: conf-l3-del-url
 labels:
   {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  l3-delete_url: |
    <!orchestratorUrl!>/api/v1/namespaces/<!lowNamespace!>/pods?fieldSelector=metadata.name=l3-<!lowInstanceId!>&gracePeriodSeconds=0
    <!orchestratorUrl!>/api/v1/namespaces/<!lowNamespace!>/configmaps/l3-bootstrap-<!lowInstanceId!>
    <!orchestratorUrl!>/api/v1/namespaces/<!lowNamespace!>/configmaps/l3-zlog-<!lowInstanceId!>
