apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-brok-jvm
  labels:
    {{- include "druid-chart.labels" . | nindent 4 }}
data:
  jvm.config: |
    -server
    -Xms512m
    -Xmx512m
    -XX:MaxDirectMemorySize=768m
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseG1GC
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=var/tmp
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
    -Dservice=broker
