apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-coord-jvm
  labels:
    {{- include "druid-chart.labels" . | nindent 4 }}
data:
  jvm.config: |
    -server
    -Xms256m
    -Xmx256m
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseG1GC
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=var/tmp
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
    -Dderby.stream.error.file=var/druid/derby.log
    -Dservice=coordinator
