apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid-chart.fullname" . }}-overlord
  labels:
    {{- include "druid-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: "overlord"
    port: 8081
    protocol: TCP
  selector:
    {{- include "druid-chart.selectorLabels" . | nindent 4 }}
