apiVersion: v1
kind: ConfigMap
metadata:
  name: coreui-config
  labels:
    {{- include "dash-front-back-end.labels" . | nindent 4 }}
data:
  config.js: |
    window.GRAFANA_URL = "{{ .Values.config.grafanaURL }}";
    window.GRAFANA_PORT = "{{ .Values.config.grafanaPort }}";
