apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dash-front-back-end.fullname" . }}-coreui-config
  labels:
    {{- include "dash-front-back-end.labels" . | nindent 4 }}
data:
  config.js: |
    window.GRAFANA_URL = "{{ tpl .Values.config.grafanaURL . }}";
    window.GRAFANA_PORT = "{{ tpl .Values.config.grafanaPort . }}";
