apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dash-front-back-end.fullname" . }}
  labels:
    {{- include "dash-front-back-end.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dash-front-back-end.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dash-front-back-end.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dash-front-back-end.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.version . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: coreui-config
              mountPath: /usr/src/dashboard/core-ui/build/config.js
              subPath: "config.js"
            - name: server-config
              mountPath: /usr/src/dashboard/server/config.json
              subPath: "config.json"
          ports:
            - name: {{ .Values.service.portname }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
            - name: {{ .Values.websocketService.portname }}
              containerPort: {{ .Values.websocketService.port }}
              #livenessProbe:
              #httpGet:
              #path: /
              #port: {{ .Values.service.port }}
              #readinessProbe:
              #httpGet:
              #path: /
              #port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: coreui-config
          configMap: 
            name: coreui-config
        - name: server-config
          configMap:
            name: server-config
