apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dash-front-back-end.fullname" . }}-server-config
  labels:
    {{- include "dash-front-back-end.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "production": {
        "config_id": "{{ .Values.config.config_id }}",
        "defaultServiceNamespace": "{{ tpl .Values.config.defaultServiceNamespace . }}",
        "defaultOranNamespace": "{{ tpl .Values.config.defaultOranNamespace . }}",
        "node_port": {{ .Values.service.port }},
        "grafanaURL": "{{ tpl .Values.config.grafanaURL . }}",
        "grafanaPort": "{{ .Values.config.grafanaPort }}",
        "nodeApiURL": "{{ tpl .Values.config.nodeApiURL . }}",
        "nodeApiPort": "{{ .Values.service.nodePort }}",
        "kafkaURL": "{{ tpl .Values.config.kafkaUrl . }}",
        "kafkaPort": "{{ tpl .Values.config.kafkaPort . }}",
        "svcOrchestratorHost": "{{ tpl .Values.config.svcOrchestratorHost . }}",
        "svcOrchestratorPort": "{{ tpl .Values.config.svcOrchestratorPort . }}",
        "svcMonitorHost": "{{ tpl .Values.config.svcMonitorHost . }}",
        "svcMonitorPort": "{{ tpl .Values.config.svcMonitorPort . }}",
        "pcixAppPodName": "{{ tpl .Values.config.pcixAppPodName . }}",
        "pcixAppPort": "{{ tpl .Values.config.pcixAppPort . }}",
        "ksqldbPodName": "{{ tpl .Values.config.ksqldbPodName . }}",
        "ksqldbPort": "{{ tpl .Values.config.ksqldbPort . }}",
        "LteRadioControllerLabel": "{{ tpl .Values.config.LteRadioControllerLabel . }}",
        "kafkaTopics": {{ tpl .Values.config.kafkaTopics . | toJson }}
      }
    }
