{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dash-front-back-end.serviceAccountName" . }}
  labels:
{{ include "dash-front-back-end.labels" . | nindent 4 }}
{{- end -}}
