{{- if .Values.websocketService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dash-front-back-end.fullname" . }}-websocket
  labels:
    {{- include "dash-front-back-end.labels" . | nindent 4 }}
spec:
  type: {{ .Values.websocketService.type }}
  ports:
    - port: {{ .Values.websocketService.port }}
      targetPort: {{ .Values.websocketService.targetPort }}
      name: {{ .Values.websocketService.portname }}
      {{- if .Values.websocketService.nodePort }}
      nodePort: {{ .Values.websocketService.nodePort }}
      {{- end }}
  selector:
    {{- include "dash-front-back-end.selectorLabels" . | nindent 4 }}
{{- end -}}
