{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acc-service-orchestrator.fullname" . }} 
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*" 
{{- end -}}
