apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-config
data:
  cellconfig.yaml: |-
    {{- $redisHostname := tpl .Values.provisioner.redis.hostname . -}}
    {{- $redisPort := tpl .Values.provisioner.redis.port . -}}
    {{ range $cellSerial, $cellName := .Values.provisioner.cells }}
    {{ $cellSerial }}:
      redis:
        hostname: {{ $redisHostname }}
        port: {{ $redisPort }}
      instance:
        filter: {{ $cellName}}
    {{ end }}
