{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acc-l2-update.serviceAccountName" . }}
  labels:
{{ include "acc-l2-update.labels" . | nindent 4 }}
{{- end -}}
