apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "network-state-monitor.fullname" . }}-config
  labels:
    {{- include "network-state-monitor.labels" . | nindent 4 }}
data:
  config.json: |-
  {{ tpl (toJson .Values.config) . | indent 4 }}
