{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-state-monitor.fullname" . }}
  labels:
    {{- include "network-state-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    {{- include "network-state-monitor.selectorLabels" . | nindent 4 }}
{{- end }}
