{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acc-service-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:  
- kind: ServiceAccount
  name: {{ include "acc-service-monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:  
  kind: ClusterRole
  name: {{ include "acc-service-monitor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
