apiVersion: v1
kind: Service
metadata:
  name: {{ include "acc-service-monitor.fullname" . }} 
  labels:
    {{- include "acc-service-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "acc-service-monitor.selectorLabels" . | nindent 4 }}
