kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "nmock.fullname" . }}
  labels:
    {{- include "nmock.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  hostPath:
     path: "{{ .Values.persistence.hostPath }}"
     type: DirectoryOrCreate
