apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmock.fullname" . }}-ssh
  labels:
    {{- include "nmock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sshService.type }}
  ports:
    - port: {{ .Values.sshService.port }}
      name:  {{ .Values.sshService.name }}
      {{ if .Values.sshService.nodePort }}
      nodePort: {{ .Values.sshService.nodePort }}
      {{ end }}
  selector:
    {{- include "nmock.selectorLabels" . | nindent 4 }}
