{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{if eq (tpl .Values.rbac.namespaced .) "false"}}Cluster{{end}}RoleBinding
metadata:
  name: {{ .Values.clusterRoleSettings.clusterRoleBindingName }}
  namespace: {{ .Release.Namespace }}
subjects:  
- kind: ServiceAccount
  name: {{ include "acc-service-monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:  
  kind: {{if eq (tpl .Values.rbac.namespaced .) "false"}}Cluster{{end}}Role
  name: {{ .Values.clusterRoleSettings.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}