{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "accelleran-xapp-statedb.serviceAccountName" . }}
  labels:
{{ include "accelleran-xapp-statedb.labels" . | nindent 4 }}
{{- end -}}
