{{- if .Values.persistence.enabled }}
{{- if eq (tpl .Values.persistence.dynamicProvisioningEnabled .) "false"}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  hostPath:
     path: "{{ .Values.persistence.hostPath }}"
     type: DirectoryOrCreate
{{- end }}
{{- end }}