apiVersion: v1
kind: ConfigMap
metadata:
  name: prov-nginx-conf
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "provision.conf" }}
  {{ . }}: 
    {{ $files.Get . | quote }}
  {{- end }}
