apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-4g-config
data:
  4GConfig.toml: |-
    protobuf_file="messages_4g.pb"

    [options]
    topic="{{ tpl .Values.configs.kafkaPublishTopic . }}"
    rewrite_timestamp="insert"
    max_len=1048756
    timeout=1000
    mask=true
    seq_mapper="{{ tpl .Values.configs.seqMapper . }}"
    threads=1
    invert_service=false
    replicate_messages=false
    compact=true
    offset="0"
    subject="topic"
    ric_id_name="{{ .Values.configs.ueRicIdName }}"
    drax_id_name="{{ .Values.configs.ueDraxIdName}}"


    [[translate]]
    topic="TOPIC_BEACONS"
    protobuf_def=".BeaconPB.Beacon_PeerMessage"

    [[translate]]
    topic="Topic_OPENRAN"
    protobuf_def=".OpenRANPB.OpenRAN_peerMessage"

    [[translate]]
    topic="Topic_OPENRAN_DATA"
    protobuf_def=".OpenRANDataPB.Message"

    [[translate]]
    topic="Topic_OPENRAN_COMMANDS"
    protobuf_def=".OpenRANCommandsPB.OpenRAN_commandMessage"

    [[translate]]
    topic="Topic_L2_STATS"
    protobuf_def=".L2StatsPB.L2StatsMessage"
