apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nkafka-helm.fullname" . }}
  labels:
    {{- include "nkafka-helm.labels" . | nindent 4 }}
  #annotations:
  #  "helm.sh/hook": post-install
  #  "helm.sh/hook-weight": "1"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nkafka-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nkafka-helm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nkafka-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.version . }}"
          env:
            - name: RUST_LOG
              value: info
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/nkafka"]
          args: ["producer", "--kafka", "{{ tpl .Values.kafkaUrl . }}", "--pb", "/messages.pb", "--group", "helm-demo", "--rewrite-time", "insert", "--seq-to-map", "--nats", "{{ tpl .Values.natsUrl . }}","--invert", "--replicate", "--threads", "1"]
#          lifecycle:
#            postStart:
#              exec:
#                command:
#                  - "sh"
#                  - "-c"
#                  - |
#                    /bin/sh <<'EOF'
#                    echo "-- Script started..." > status.log
#                    apk update && apk add curl
#
#                    until curl -s {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor ; do sleep 6; done
#
#                    read response <<< $(curl -s {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor)
#
#                    EOF
#
#                    if echo "$response" | grep "test2" ; then
#                      echo "test2 OK" >> status.log
#                      until curl -f -XPOST {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor/test2/reset ; do sleep 6; done
#                    else
#                      echo "test2 BAD" >> status.log
#                      until curl -f -X POST -H "Content-Type: application/json" -d @supervisor.json {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor; do sleep 6; done
#                      until curl -f -XPOST {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor/test2/reset ; do sleep 6; done
#                    fi
#
#                    if echo "$response" | grep "state" ; then
#                      echo "state OK" >> status.log
#                      until curl -f -XPOST {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor/state/reset ; do sleep 6; done
#                    else
#                      echo "state BAD" >> status.log
#                      until curl -f -X POST -H "Content-Type: application/json" -d @state-supervisor.json {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor; do sleep 6; done
#                      until curl -f -XPOST {{ tpl .Values.druidOverlordUrl . }}/druid/indexer/v1/supervisor/state/reset ; do sleep 6; done
#                    fi
#
#                    echo "-- Script finished!" >> status.log
#
#                    EOF
#          ports:
#            - name: http
#              containerPort: 80
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
