global:
  kubeIp: "10.55.6.3"
  enable4G: true
  enable5G: true
dash-front-back-end:
  config:
    grafanaURL: "10.55.6.3"
    nodeApiURL: "10.55.6.3"
    apiUrl: "10.55.6.3"
acc-5g-infrastructure:
  metallb:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 10.55.6.20-10.55.6.60
  jaeger:
    enabled: true
nkafka-5g:
  configs:
    logLevel: debug

acc-4g-infrastructure:
  provisioner-dhcp:
    enabled: false
    configuration:
      interface: eno1
  configurator:
    enabled: false

