{{- $values := index .Values "instance-scaler" -}}

{{- if ($values.serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ ($values.serviceAccount).enabled | default (include "cell-wrapper.instance-scaler.fullname" .) | quote }}
  labels:
    {{- include "cell-wrapper.instance-scaler.labels" . | nindent 4 }}
  {{- with ($values.serviceAccount).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if ($values.rbac).enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cell-wrapper.instance-scaler.fullname" . | quote }}
  labels:
    {{- include "cell-wrapper.instance-scaler.labels" . | nindent 4 }}
rules:
  {{- tpl (toYaml $values.rbac.rules) $ | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cell-wrapper.instance-scaler.fullname" . | quote }}
  labels:
    {{- include "cell-wrapper.instance-scaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cell-wrapper.instance-scaler.fullname" . | quote }}
subjects:
- kind: ServiceAccount
  name: {{ ($values.serviceAccount).enabled | default (include "cell-wrapper.instance-scaler.fullname" .) | quote }}
{{- end -}}
