{{- if .Values.e2tsctp.ingress.enabled -}}
{{- $fullName := include "e2t.fullname" . -}}
{{- $svcPort := .Values.e2tsctp.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    helm.sh/chart: {{ include "e2t.chart" . }}
    app.kubernetes.io/name: {{ include "e2t.name" . }}-sctp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    drax/role: e2
    drax/name: e2t
    drax/component-name: {{ .Chart.Name }}-sctp
    drax/component-version: {{ .Chart.Version }}
    drax/instanceId: "{{ tpl .Values.e2tsctp.bootstrapId . }}"
  {{- with .Values.e2tsctp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.e2tsctp.ingress.tls }}
  tls:
    {{- range .Values.e2tsctp.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.e2tsctp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
