{{- if .Values.e2tsctp.sctpService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "five-g-appl.fullname" . }}-sctp
  labels:
    helm.sh/chart: {{ include "five-g-appl.chart" . }}
    app.kubernetes.io/name: {{ include "five-g-appl.name" . }}-sctp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    drax/role: e2
    drax/name: e2t
    drax/component-name: {{ .Chart.Name }}-sctp
    drax/component-version: {{ .Chart.Version }}
    drax/instanceId: "{{ tpl .Values.global.bootstrapId . }}"
    drax/service-name: {{ tpl .Values.e2tsctp.sctpService.name . }}
spec:
  type: {{ .Values.e2tsctp.sctpService.type }}
  {{ if .Values.e2tsctp.sctpService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ tpl .Values.e2tsctp.sctpService.externalTrafficPolicy . }}
  {{ end }}
  ports:
    - port: {{ .Values.e2tsctp.sctpService.port}}
      protocol: {{ .Values.e2tsctp.sctpService.protocol }}
      name: {{ tpl .Values.e2tsctp.sctpService.name . }}
      {{ if contains "NodePort" .Values.e2tsctp.sctpService.type }}
      nodePort: {{ .Values.e2tsctp.sctpService.nodePort }}
      {{ end }}
  {{ if .Values.e2tsctp.sctpService.loadBalancerIP }}
  loadBalancerIP: {{ tpl .Values.e2tsctp.sctpService.loadBalancerIP . }}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "five-g-appl.name" . }}-sctp
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
