apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "five-g-appl.fullname" . }}
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "five-g-appl.fullname" . }}-service
  {{- if not .Values.e2tap.autoscaling.enabled }}
  replicas: {{ tpl .Values.e2tap.numOfE2Nodes . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "five-g-appl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.e2tap.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "five-g-appl.labels" . | nindent 8 }}
    spec:
      {{- with .Values.e2tap.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "five-g-appl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.e2tap.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.e2tap.securityContext | nindent 12 }}
          image: "{{ .Values.e2tap.image.repository }}:{{ tpl .Values.e2tap.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.e2tap.image.pullPolicy }}
          {{ if .Values.e2tap.developerMode.enabled }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'
              echo "export __APPID=e2-ap-${HOSTNAME##*-}" > /home/accelleran/5G/dev/environment.sh
              chmod +x /home/accelleran/5G/dev/environment.sh
              while true; do sleep 30; done;
              EOF
          {{ else }}
          command:
            - sh
            - "-c"
            - |
              /bin/sh <<'EOF'
              echo e2-ap-${HOSTNAME##*-}
              __APPID=e2-ap-${HOSTNAME##*-} {{ .Values.e2tap.cmd }} {{- if .Values.e2tap.args }}{{ range .Values.e2tap.args }} {{ .name }} {{ .value }}{{ end }}{{- end }}
              EOF
          {{ end }}
          env:
            - name: NATS_SERVICE_URL
              value: nats://{{ tpl .Values.natsHostname . }}:{{ tpl .Values.natsPort . }}
            - name: ZLOG_CONF_PATH
              value: /home/accelleran/5G/zlog.conf
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.e2tap.bootstrapFile }}
            - name: JAEGER_AGENT_HOST
              value: {{ tpl .Values.jaegerAgentHost . }}
            - name: __APPNAME
              value: e2Ap
            {{- if .Values.e2tap.extraEnvs }}
            {{ toYaml .Values.e2tap.extraEnvs | nindent 12 }}
            {{- end }}
#          ports:
#            - name: {{ tpl .Values.e2tap.service.name . }}
#              containerPort: {{ .Values.e2tap.service.port}}
#              protocol: {{ .Values.e2tap.service.protocol }}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
            - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
              mountPath: /home/accelleran/5G/zlog.conf
              subPath: "zlog.conf"
            - name: {{ include "five-g-appl.fullname" . }}-bootstrap
              mountPath: {{ .Values.e2tap.bootstrapFile }}
              subPath: "bootstrap.txt"
            {{ if and (.Values.e2tap.developerMode.enabled) (.Values.e2tap.developerMode.hostPath) }}
            - name: dev-work-dir
              mountPath: /home/accelleran/5G/dev/
            {{ end }}
          resources:
            {{- toYaml .Values.e2tap.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'pkill -15 -e {{ .Values.e2tap.cmd | trimPrefix "./" | trimSuffix ".exe" | trunc 15  }}' ]
      {{- if or (.Values.e2tap.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.e2tap.nodeSelector }}
          {{- toYaml .Values.e2tap.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Value.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
      {{- with .Values.e2tap.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.e2tap.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-zlog-conf

        - name: {{ include "five-g-appl.fullname" . }}-bootstrap
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-bootstrap

        {{ if and (.Values.e2tap.developerMode.enabled) (.Values.e2tap.developerMode.hostPath) }}
        - name: dev-work-dir
          hostPath:
            path: {{ .Values.e2tap.developerMode.hostPath }}
        {{ end }}
