{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntp-server.fullname" . }}
  labels:
    {{- include "ntp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: UDP
      name: http
  selector:
    {{- include "ntp-server.selectorLabels" . | nindent 4 }}
{{- end }}
