apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.serviceName . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
