apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oran-clustercontrol.fullname" . }}-check-netconf
  labels:
    {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  check-netconf.py: |
    from netconf_client.connect import connect_ssh
    from netconf_client.ncclient import Manager
    import time

    HOST = "{{ .Values.jobs.netconfConfig.netconfHost }}"
    PORT = 830

    while True:
        try:
            session = connect_ssh(host=HOST, port=PORT, username="helm", password="helm")
            mgr = Manager(session, timeout=120)
            print(session.server_capabilities)
            print('[CHECK-NETCONF] Succesfuly connected to NetConf Server.')
            break
        except:
            print('[CHECK-NETCONF] Failed to connect to the NetConf Server!')

        time.sleep(1)
