apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oran-clustercontrol.fullname" . }}-4g-netconf-delete-config
  labels:
    {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  4grc-netconf-delete-config.py: |
    from netconf_client.connect import connect_ssh
    from netconf_client.ncclient import Manager
    import time

    HOST = "{{ .Values.jobs.netconfConfig.netconfHost }}"
    PORT = 830

    session = connect_ssh(host=HOST, port=PORT, username="helm", password="helm")
    mgr = Manager(session, timeout=120)
    rc_config = """<config>
                   <enb-internal xmlns="http://accelleran.com/ns/yang/accelleran-enb-internal" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="delete" />
                   </config>
                """
    try:
      print(mgr.edit_config(config=rc_config,target='running', default_operation=None))
      print("Successfully deleted the 4G Radio Controller Configuration!")
    except Exception as e:
      print(e)
