apiVersion: v1
kind: ConfigMap
metadata:
 name: conf-l3-service-del-url
 labels:
   {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  l3-service-delete_url: |
    <!orchestratorUrl!>/api/v1/namespaces/<!lowNamespace!>/services/netconf-<!lowInstanceId!>
