apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ include "influxdb.fullname" . }}-api
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: api
    port: {{ .Values.config.http.bind_address | default 8086 }}
    targetPort: api
    nodePort: {{ .Values.service.apiNodePort }}
  selector:
    {{- include "influxdb.selectorLabels" . | nindent 4 }}

