{{- if and .Values.backup.enabled .Values.backup.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "influxdb.fullname" . }}-backup
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backup.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size | quote }}
{{- if (tpl .Values.backup.persistence.storageClass .) }}
{{- if (eq "-" (tpl .Values.backup.persistence.storageClass .)) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ tpl .Values.backup.persistence.storageClass . }}"
{{- end }}
{{- end }}
{{- end }}
