apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "influxdb.fullname" . }}-del-pvc 
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      {{- if or (.Values.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.nodeSelector }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
      containers:
      - name: post-delete-job
        image: {{ .Values.postDeleteJob.image }}
        command: ["kubectl"]
        args:
        - "delete"
        - "pvc"
        - "-l"
        - "app.kubernetes.io/name={{ include "influxdb.name" . }}"
      serviceAccountName: {{ include "influxdb.fullname" . }}-pvc-deleter-sa
      securityContext:
        runAsUser: 0
