{{- if not .Values.persistence.dynamicProvisioningEnabled}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
     path: "{{ .Values.persistence.hostPath }}/{{ include "influxdb.fullname" . }}"
     type: DirectoryOrCreate
{{- end -}}