apiVersion: rbac.authorization.k8s.io/v1
kind: {{if eq (tpl .Values.rbac.namespaced .) "false"}}Cluster{{end}}Role
metadata:
  name: {{ include "influxdb.fullname" . }}-pvc-deleter-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "delete", "deletecollection"]
