apiVersion: rbac.authorization.k8s.io/v1
kind: {{if eq (tpl .Values.rbac.namespaced .) "false"}}Cluster{{end}}RoleBinding
metadata:
  name: {{ include "influxdb.fullname" . }}-pvc-deleter-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "influxdb.fullname" . }}-pvc-deleter-role
subjects:
- kind: ServiceAccount
  name: {{ include "influxdb.fullname" . }}-pvc-deleter-sa
