apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "influxdb.fullname" . }}-pvc-deleter-sa
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

