apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-keycloak-ingress
  labels:
    {{- include "keycloak-ingress.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-keycloak-http
                port:
                  number: 80
