apiVersion: v1
kind: Secret
metadata:
  name: "keycloak-secret"
type: Opaque
data:
  # Retrieve the secret data using lookup function and when not exists, return an empty dictionary as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "keycloak-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $keycloakSecret to existing secret data or generate a random one when not exists
  {{- $keycloakSecret := (get $secretData "keycloak-secret") | default (randAscii 16 | b64enc) }}
  KEYCLOAK_PASSWORD: {{ $keycloakSecret | quote }}
