{{- if not .Values.persistence.dynamicProvisioningEnabled}}
{{- if .Values.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  hostPath:
     path: "{{ .Values.persistence.hostPath }}"
     type: DirectoryOrCreate
{{- end }}
{{- end }}
