{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{if eq (tpl .Values.rbac.namespaced .) "false"}}Cluster{{end}}Role
metadata:
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.rbac.pspEnabled }}
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "loki.fullname" . }}]
{{- end }}
{{- end }}

