apiVersion: v1
kind: ConfigMap
metadata:
  name: acc-druid-sv
  labels:
    {{- include "druid-chart.labels" . | nindent 4 }}
data:
  supervisor.json: |
    {
      "dataSchema": {
        "dataSource": "test2",
        "timestampSpec": {
          "column": "timestamp",
          "format": "nano",
          "missingValue": null
        },
        "dimensionsSpec": {
          "dimensions": [
            {
              "type": "string",
              "name": "beaconInfo.componentId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "beaconInfo.interval",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "string",
              "name": "beaconInfo.serviceInfo",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "beaconInfo.serviceType",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "blerReport.cellId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "blerReport.dlBler",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "string",
              "name": "blerReport.ueRicId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "blerReport.ulBler",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "string",
              "name": "cqiReport.cellId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.0",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.1",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.2",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.3",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.4",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.5",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.6",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.7",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.8",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.9",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.10",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.11",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiList.12",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.cqiListSize",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "string",
              "name": "cqiReport.ueRicId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "cqiReport.widebandCqi",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "long",
              "name": "fromChannelId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "long",
              "name": "messageType",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "string",
              "name": "throughputReport.cellId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "throughputReport.dlThroughput",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "throughputReport.ueRicId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "throughputReport.ulThroughput",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "type",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "ueMeasurement.attached",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "string",
              "name": "ueMeasurement.cellId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "long",
              "name": "ueMeasurement.rsrp",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "long",
              "name": "ueMeasurement.rsrq",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": false
            },
            {
              "type": "string",
              "name": "ueMeasurement.ueCellId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "ueMeasurement.ueRicId",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "service.id",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "service.serviceType",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            },
            {
              "type": "string",
              "name": "service.state",
              "multiValueHandling": "SORTED_ARRAY",
              "createBitmapIndex": true
            }
          ],
          "dimensionExclusions": [
            "timestamp"
          ]
        },
        "metricsSpec": [],
        "granularitySpec": {
          "type": "uniform",
          "segmentGranularity": "HOUR",
          "queryGranularity": {
            "type": "none"
          },
          "rollup": false,
          "intervals": null
        },
        "transformSpec": {
          "filter": null,
          "transforms": [
            {
              "type": "expression",
              "name": "ueMeasurement.attached",
              "expression": "\"ueMeasurement.ueCellId\" == \"ueMeasurement.cellId\""
            }
          ]
        }
      },
      "ioConfig": {
        "topic": "test2",
        "inputFormat": {
          "type": "json",
          "flattenSpec": {
            "useFieldDiscovery": true,
            "fields": [
              {
                "type": "path",
                "name": "beaconInfo.componentId",
                "expr": "$.beaconInfo.componentId"
              },
              {
                "type": "path",
                "name": "beaconInfo.interval",
                "expr": "$.beaconInfo.interval"
              },
              {
                "type": "path",
                "name": "beaconInfo.serviceInfo",
                "expr": "$.beaconInfo.serviceInfo"
              },
              {
                "type": "path",
                "name": "beaconInfo.serviceType",
                "expr": "$.beaconInfo.serviceType"
              },
              {
                "type": "path",
                "name": "blerReport.cellId",
                "expr": "$.blerReport.cellId"
              },
              {
                "type": "path",
                "name": "blerReport.dlBler",
                "expr": "$.blerReport.dlBler"
              },
              {
                "type": "path",
                "name": "blerReport.ueRicId",
                "expr": "$.blerReport.ueRicId"
              },
              {
                "type": "path",
                "name": "blerReport.ulBler",
                "expr": "$.blerReport.ulBler"
              },
              {
                "type": "path",
                "name": "cqiReport.cellId",
                "expr": "$.cqiReport.cellId"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.0",
                "expr": "$.cqiReport.cqiList.0"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.1",
                "expr": "$.cqiReport.cqiList.1"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.2",
                "expr": "$.cqiReport.cqiList.2"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.3",
                "expr": "$.cqiReport.cqiList.3"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.4",
                "expr": "$.cqiReport.cqiList.4"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.5",
                "expr": "$.cqiReport.cqiList.5"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.6",
                "expr": "$.cqiReport.cqiList.6"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.7",
                "expr": "$.cqiReport.cqiList.7"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.8",
                "expr": "$.cqiReport.cqiList.8"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.9",
                "expr": "$.cqiReport.cqiList.9"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.10",
                "expr": "$.cqiReport.cqiList.10"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.11",
                "expr": "$.cqiReport.cqiList.11"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiList.12",
                "expr": "$.cqiReport.cqiList.12"
              },
              {
                "type": "path",
                "name": "cqiReport.cqiListSize",
                "expr": "$.cqiReport.cqiListSize"
              },
              {
                "type": "path",
                "name": "cqiReport.ueRicId",
                "expr": "$.cqiReport.ueRicId"
              },
              {
                "type": "path",
                "name": "cqiReport.widebandCqi",
                "expr": "$.cqiReport.widebandCqi"
              },
              {
                "type": "path",
                "name": "throughputReport.cellId",
                "expr": "$.throughputReport.cellId"
              },
              {
                "type": "path",
                "name": "throughputReport.dlThroughput",
                "expr": "$.throughputReport.dlThroughput"
              },
              {
                "type": "path",
                "name": "throughputReport.ueRicId",
                "expr": "$.throughputReport.ueRicId"
              },
              {
                "type": "path",
                "name": "throughputReport.ulThroughput",
                "expr": "$.throughputReport.ulThroughput"
              },
              {
                "type": "path",
                "name": "ueMeasurement.cellId",
                "expr": "$.ueMeasurement.cellId"
              },
              {
                "type": "path",
                "name": "ueMeasurement.rsrp",
                "expr": "$.ueMeasurement.rsrp"
              },
              {
                "type": "path",
                "name": "ueMeasurement.rsrq",
                "expr": "$.ueMeasurement.rsrq"
              },
              {
                "type": "path",
                "name": "ueMeasurement.ueCellId",
                "expr": "$.ueMeasurement.ueCellId"
              },
              {
                "type": "path",
                "name": "ueMeasurement.ueRicId",
                "expr": "$.ueMeasurement.ueRicId"
              },
              {
                "type": "path",
                "name": "service.id",
                "expr": "$.service.id"
              },
              {
                "type": "path",
                "name": "service.serviceType",
                "expr": "$.service.serviceType"
              },
              {
                "type": "path",
                "name": "service.state",
                "expr": "$.service.state"
              }
        ]
          },
          "featureSpec": {}
        },
        "replicas": 1,
        "taskCount": 1,
        "taskDuration": "PT3600S",
        "consumerProperties": {
          "bootstrap.servers": "{{ tpl .Values.kafkaUrl . }}"
        },
        "pollTimeout": 100,
        "startDelay": "PT5S",
        "period": "PT30S",
        "useEarliestOffset": false,
        "completionTimeout": "PT1800S",
        "lateMessageRejectionPeriod": null,
        "earlyMessageRejectionPeriod": null,
        "lateMessageRejectionStartDateTime": null,
        "stream": "test2",
        "useEarliestSequenceNumber": false,
        "type": "kafka"
      },
      "tuningConfig": {
        "type": "kafka",
        "maxRowsInMemory": 1000000,
        "maxBytesInMemory": 0,
        "maxRowsPerSegment": 5000000,
        "maxTotalRows": null,
        "intermediatePersistPeriod": "PT10M",
        "basePersistDirectory": "/opt/apache-druid-0.17.0-SNAPSHOT/var/tmp/druid-realtime-persist2564984710534084110",
        "maxPendingPersists": 0,
        "indexSpec": {
          "bitmap": {
            "type": "concise"
          },
          "dimensionCompression": "lz4",
          "metricCompression": "lz4",
          "longEncoding": "longs"
        },
        "indexSpecForIntermediatePersists": {
          "bitmap": {
            "type": "concise"
          },
          "dimensionCompression": "lz4",
          "metricCompression": "lz4",
          "longEncoding": "longs"
        },
        "buildV9Directly": true,
        "reportParseExceptions": false,
        "handoffConditionTimeout": 0,
        "resetOffsetAutomatically": false,
        "segmentWriteOutMediumFactory": null,
        "workerThreads": null,
        "chatThreads": null,
        "chatRetries": 8,
        "httpTimeout": "PT10S",
        "shutdownTimeout": "PT80S",
        "offsetFetchPeriod": "PT30S",
        "intermediateHandoffPeriod": "P2147483647D",
        "logParseExceptions": false,
        "maxParseExceptions": 2147483647,
        "maxSavedParseExceptions": 0,
        "skipSequenceNumberAvailabilityCheck": false,
        "repartitionTransitionDuration": "PT120S"
      },
      "type": "kafka"
    }
