apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-log4j2-task
  labels:
    {{- include "druid-chart.labels" . | nindent 4 }}
data:
  log4j2-task.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
        <Appenders>
           <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
            </Console>                                                                                                        
        </Appenders>                                                                                                          
        <Loggers>                                                                                                             
            <Root level="error">                                                                                               
                <AppenderRef ref="Console"/>                                                                                  
            </Root>                                                                                                           
        </Loggers>                                                                                                            
    </Configuration>
