apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-log4j2
  labels:
    {{- include "druid-chart.labels" . | nindent 4 }}
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">
     <Appenders>
     <RollingFile name="RollingFile" fileName="var/sv/${sys:service}-service.log" filePattern="var/sv/${sys:service}-service-%d{yyyy-MM-dd}.%i.log.gz">
     <PatternLayout>
     <Pattern>%d{ISO8601} %p [%t] %c - %m%n</Pattern>
     </PatternLayout>
     <Policies>
     <TimeBasedTriggeringPolicy interval="1" modulate="true"/>
     <SizeBasedTriggeringPolicy size="100 MB"/>
     </Policies>
     <DefaultRolloverStrategy max="10"/>
     </RollingFile>
     </Appenders>
     <Loggers>
     <Root level="error">
     <AppenderRef ref="RollingFile"/>
     </Root>
     </Loggers>
    </Configuration>
