apiVersion: v1
kind: ConfigMap
metadata:
 name: l3-fdd-start-config
 labels:
   {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  l3start: |
    #! /bin/bash -x

    GIT_ROOT=/data

    INSTANCE_NAME=$1
    INSTANCE_DIR=${GIT_ROOT}/l3-${INSTANCE_NAME}
    mkdir -p ${INSTANCE_DIR}

    cd ${INSTANCE_DIR}

    echo "redis.hostname:{{ tpl .Values.config.redis.hostname . }}" | tee ${INSTANCE_DIR}/l3.bootstrap
    echo "redis.port:{{ .Values.config.redis.port }}" | tee -a ${INSTANCE_DIR}/l3.bootstrap
    echo "instance.filter:${INSTANCE_NAME}" | tee -a ${INSTANCE_DIR}/l3.bootstrap

    tar xf ${GIT_ROOT}/l3-fdd/links.tar
 
    ZLOG_CONF_PATH=zlog_syslog.conf \
    BOOTSTRAP_FILENAME=l3.bootstrap \
    NETCONF_MODEL_PATH=${GIT_ROOT}/netconf-models \
    NETCONF_HOST_KEY_PATH=${GIT_ROOT}/.ssh/hostkey \
    LIBYANG_SEARCH_DIR=${GIT_ROOT}/netconf-models \
    LIBYANG_USER_TYPES_PLUGINS_DIR=${GIT_ROOT}/libs/libyang/user_types \
    LIBYANG_EXTENSIONS_PLUGINS_DIR=${GIT_ROOT}/libs/libyang/extensions \
    LD_LIBRARY_PATH=${GIT_ROOT}/libs ./l3service

    
