apiVersion: v1
kind: Service
metadata:
  name: {{ include "acc-service-orchestrator.fullname" . }}
  labels:
    {{- include "acc-service-orchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: {{ include "acc-service-orchestrator.fullname" . }}
  selector:
    {{- include "acc-service-orchestrator.selectorLabels" . | nindent 4 }}
