apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acc-common.fullname" . }}-du-nodeh
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
data:
  {{ .Values.baseConfig.du.nodeh.file }}: |-
    {{- if .Values.baseConfig.du.nodeh.data }}
    {{- .Values.baseConfig.du.nodeh.data | nindent 4 }}
    {{- else }}
    {
      "Services": {
        "FAPService": {
          "1": {
            "CellConfig": {
              "NR": {
                "RAN": {
                  "CUNumberOfEntries": 0,
                  "CUUPNumberOfEntries": 0,
                  "DU": {
                    "1": {
                      "DEBUG": {
                        "NphyPcapCaptureDisabled": true
                      },
                      "F1": {
                        "IPAddresses": "127.0.0.1",
                        "Nssai1stPlmnInfo": {
                          "1": {
                            "NssaiList": ""
                          }
                        },
                        "Nssai1stPlmnInfoNumberOfEntries": 1,
                        "PlmnInfo": {
                          "1": {
                            "CellIdentity": "1",
                            "PlmnIdentity": "",
                            "RanAreaCode": 1,
                            "TrackingAreaCode": 1
                          }
                        },
                        "PlmnInfoNumberOfEntries": 1
                      },
                      "General": {
                        "CellIdx": 0,
                        "ChannelBwRb": 273,
                        "ChannelNrArfcn": 636684,
                        "DuOwnIPAddress": "127.0.0.1",
                        "Enable": true,
                        "FreqSyncTimeout": 0,
                        "MaxMimoLayers": 2,
                        "MaxUlMimoLayers": 2,
                        "NrMode": "TDD",
                        "OperatingBandsDl": "n78",
                        "OperatingBandsUl": "n78",
                        "PhyCellId": 1,
                        "SyncSource": "GPS",
                        "TxPowerPerPathDBmx10": 180
                      },
                      "MAC": {
                        "BwpDl": {
                          "1": {
                            "Nrb": 273,
                            "OffsetToCrb0": 0,
                            "Scs": 30
                          }
                        },
                        "BwpDlNumberOfEntries": 1,
                        "BwpUl": {
                          "1": {
                            "Nrb": 273,
                            "OffsetToCrb0": 0,
                            "Scs": 30
                          }
                        },
                        "BwpUlNumberOfEntries": 1,
                        "Pcch": {
                          "N": "One",
                          "NandPagingFrameOffset": "OneT",
                          "Offset": 0,
                          "PagingCycle": "RF128"
                        },
                        "Rach": {
                          "NumContentionBasedPreambles": 32,
                          "TotalNumberOfPreambles": 60
                        },
                        "SearchSpace0": 0,
                        "TDD": {
                          "TDDSlotsDL": 7,
                          "TDDSlotsPeriod": 10,
                          "TDDSlotsUL": 2
                        }
                      },
                      "RRC": {
                        "PRach": {
                          "NumFdPrachOccasions": 1,
                          "NumTdPrachOccasions": 3,
                          "OffsetSfn": 0,
                          "PeriodSfn": 1,
                          "PrachRootSequenceIndex": 0,
                          "PreambleFormat": "PreambleFormatA2",
                          "preambleReceivedTargetPower": -90
                        },
                        "QQualMin": -30,
                        "QRxLevMin": -70,
                        "SSB": {
                          "GroupPresence": 255,
                          "InOneGroup": 1,
                          "SsbPeriodicity": "SsbPeriod20ms",
                          "TxAntennaLoss": -20
                        },
                        "TimersAndConsts": {
                          "TInactivity": 0
                        }
                      }
                    }
                  },
                  "DUNumberOfEntries": 1
                }
              }
            }
          }
        }
      }
    }
    {{- end }}
