apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acc-common.fullname" . }}
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
spec:
  replicas: {{ include "cw-inst.replicas" . }}
  selector:
    matchLabels:
      {{- include "acc-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "acc-common.labels.5g" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.cmd }}
          command:
            - "{{ .Values.cmd }}"
          {{- end }}
          {{- if gt (len .Values.args) 0 }}
          args:
            {{- range .Values.args }}
            - "{{ .name }}"
            - "{{ .value }}"
            {{- end }}
          {{- end }}
          env:
            - name: NATS_SERVICE_URL
              value: "nats://{{ tpl .Values.nats.url . }}:{{ tpl .Values.nats.port . }}"
            - name: BOOTSTRAP_FILENAME
              value: "{{ .Values.bootstrapFile }}"
            - name: __APPID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAEGER_AGENT_HOST
              value: "{{ tpl .Values.jaegerAgentHost . }}"
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ include "acc-common.fullname" . }}-bootstrap
              mountPath: "{{ .Values.bootstrapFile }}/"
              subPath: "bootstrap.txt"
              readOnly: true
            - name: {{ include "acc-common.fullname" . }}-ssh-key
              mountPath: "/home/accelleran/5G/ssh/"
              readOnly: true
            {{- range $vendor, $v := .Values.baseConfig.vendors }}
            {{- range $v }}
            - name: {{ include "acc-common.fullname" $ }}-{{ $vendor }}
              mountPath: "{{ $.Values.baseConfig.configDir }}/{{ $vendor }}/{{ .file }}"
              subPath: "{{ .file }}"
              readOnly: true
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or (.Values.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.nodeSelector }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "acc-common.fullname" . }}-bootstrap
          configMap:
            name: {{ include "acc-common.fullname" . }}-bootstrap
        - name: {{ include "acc-common.fullname" . }}-ssh-key
          secret:
            secretName: {{ tpl .Values.secrets.sshKey . }}
            defaultMode: 256
        {{- range $vendor, $v := .Values.baseConfig.vendors }}
        - name: {{ include "acc-common.fullname" $ }}-{{ $vendor }}
          configMap:
            name: {{ include "acc-common.fullname" $ }}-{{ $vendor }}
        {{- end }}
