kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  hostPath:
     #path: "{{ .Values.persistence.hostPath }}/{{ include "nginx.fullname" . }}"
     path: "{{ .Values.persistence.hostPath }}/provisioner"
     type: DirectoryOrCreate
