{{ if .Values.services.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acc-kafka.fullname" . }}
  labels:
    {{- include "acc-kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      {{ if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ tpl .Values.service.loadBalancerIP . }}
  {{ end }}
  selector:
    {{- include "acc-kafka.selectorLabels" . | nindent 4 }}
{{ end }}