apiVersion: v2
name: ric
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.16

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.16

# Dependencies
dependencies:
  - name: druid
    version: 0.4.2
    repository: https://accelleran.github.io/helm-charts/
  - name: kafka
    condition: kafka.enabled
    version: 0.20.9
    repository: https://accelleran.github.io/helm-charts/
  - name: nkafka-helm
    version: 0.3.1
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-sys-dashboard
    version: 1.6.6
    repository: https://accelleran.github.io/helm-charts/
  - name: dash-front-back-end
    version: 0.16.2
    repository: https://accelleran.github.io/helm-charts/
  - name: loki-stack
    version: 0.36.2
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-service-monitor
    condition: acc-service-monitor.enabled
    version: 0.3.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-service-orchestrator
    condition: acc-service-orchestrator.enabled
    version: 0.4.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-state-db
    condition: acc-state-db.enabled
    version: 0.4.10
    repository: https://accelleran.github.io/helm-charts/
  - name: influxdb
    condition: influxdb.enabled
    version: 4.8.5
    repository: https://accelleran.github.io/helm-charts/
  - name: vector
    condition: vector.enabled
    version: 0.2.1
    repository: https://accelleran.github.io/helm-charts/


