apiVersion: v2
name: ric
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.5.12

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.5.12

# Dependencies
dependencies:
  - name: acc-kafka
    condition: acc-kafka.enabled
    version: 0.2.0
    repository: https://accelleran.github.io/helm-charts/
  - name: nkafka-4g
    version: 2.1.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-sys-dashboard
    version: 3.2.6
    repository: https://accelleran.github.io/helm-charts/
  - name: dash-front-back-end
    version: 0.23.0
    repository: https://accelleran.github.io/helm-charts/
  - name: loki-stack
    version: 0.43.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-service-monitor
    condition: acc-service-monitor.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-service-orchestrator
    condition: acc-service-orchestrator.enabled
    version: 0.6.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-state-db
    condition: acc-state-db.enabled
    version: 0.9.0
    repository: https://accelleran.github.io/helm-charts/
  - name: influxdb
    condition: influxdb.enabled
    version: 5.0.0
    repository: https://accelleran.github.io/helm-charts/
  - name: vector
    condition: vector.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/
  - name: vectorfiveg
    condition: vectorfiveg.enabled
    version: 0.4.3
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-fiveg-pmcounters
    condition: acc-fiveg-pmcounters.enabled
    version: 0.2.1
    repository: https://accelleran.github.io/helm-charts/



