apiVersion: v2
name: ric
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 3.0.0-rc4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 3.0.0-rc4

# Dependencies
dependencies:
  - name: acc-kafka
    condition: acc-kafka.enabled
    version: 0.3.1
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-kminion
    condition: acc-kminion.enabled
    version: 1.5.0
    repository: https://accelleran.github.io/helm-charts/
  - name: nkafka-4g
    condition: nkafka-4g.enabled
    version: 3.7.1
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-sys-dashboard
    version: 3.4.0
    repository: https://accelleran.github.io/helm-charts/
  - name: dash-front-back-end
    version: 2.0.3
    repository: https://accelleran.github.io/helm-charts/
  - name: loki-stack
    version: 0.43.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-service-monitor
    condition: acc-service-monitor.enabled
    version: 0.6.0
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-service-orchestrator
    condition: acc-service-orchestrator.enabled
    version: 1.1.1
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-state-db
    condition: acc-state-db.enabled
    version: 0.14.5
    repository: https://accelleran.github.io/helm-charts/
  - name: influxdb
    condition: influxdb.enabled
    version: 5.0.1
    repository: https://accelleran.github.io/helm-charts/
  - name: vector
    condition: vector.enabled
    version: 0.7.0
    repository: https://accelleran.github.io/helm-charts/
  - name: vectorfiveg
    condition: vectorfiveg.enabled
    version: 0.5.2
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-fiveg-pmcounters
    condition: acc-fiveg-pmcounters.enabled
    version: 0.4.1
    repository: https://accelleran.github.io/helm-charts/
  - name: acc-5g-infrastructure
    condition: global.enable5G
    version: 0.2.0
    repository: https://accelleran.github.io/5g-helm-charts
  - name: nkafka-5g
    condition: global.enable5G
    version: 0.5.0-beta
    repository: https://accelleran.github.io/5g-helm-charts





