apiVersion: v2
name: ric
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 6.0.0-alpha

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 6.0.0-alpha

# Dependencies
dependencies:
  - name: metrics-server
    condition: metrics-server.enabled
    version: 2.11.3
    repository: file://../metrics-server
  - name: acc-kafka
    condition: acc-kafka.enabled
    version: 0.3.2
    repository: file://../acc-kafka
  - name: acc-kminion
    condition: acc-kminion.enabled
    version: 1.5.1
    repository: file://../acc-kminion
  - name: acc-sys-dashboard
    condition: acc-sys-dashboard.enabled
    version: 3.4.11
    repository: file://../acc-sys-dashboard
  - name: dash-front-back-end
    condition: dash-front-back-end.enabled
    version: 4.2.0-rc.1
    repository: file://../dash-front-back-end
  - name: loki-stack
    version: 0.43.1
    repository: file://../loki-stack
  - name: acc-service-monitor
    condition: acc-service-monitor.enabled
    version: 0.6.1
    repository: file://../acc-service-monitor
  - name: acc-service-orchestrator
    condition: acc-service-orchestrator.enabled
    version: 2.3.0-rc.1
    repository: file://../acc-service-orchestrator
  - name: acc-state-db
    condition: global.enable4G
    version: 0.14.5
    repository: file://../accelleran-xapp-statedb
  - name: influxdb
    condition: influxdb.enabled
    version: 5.0.3
    repository: file://../influxdb
  - name: vector
    condition: vector.enabled
    version: 0.7.1
    repository: file://../vector
  - name: vectorfiveg
    condition: vectorfiveg.enabled
    version: 0.6.2
    repository: file://../vector-5g
  - name: acc-fiveg-pmcounters
    condition: acc-fiveg-pmcounters.enabled
    version: 0.5.1
    repository: file://../acc-fiveg-pmcounters
  - name: acc-5g-infrastructure
    condition: global.enable5G
    version: 3.0.0
    repository: https://accelleran.github.io/5g-helm-charts
  - name: golang-nkafka
    alias: golang-nkafka-4g
    condition: global.enable4G
    version: 1.0.0-alpha
    repository: file://../golang-nkafka
  - name: golang-nkafka
    alias: golang-nkafka-5g
    condition: global.enable5G
    version: 1.0.0-alpha
    repository: file://../golang-nkafka
  - name: acc-4g-infrastructure
    condition: global.enable4G
    version: 5.1.0
    repository: file://../acc-4g-infrastructure
  - name: keycloak-ingress
    condition: ingress.enabled
    version: 0.1.1
    repository: file://../keycloak-ingress
