apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-netconf-init-config-job-reader-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Release.Name }}-netconf-init-config-job-reader"
subjects:
  - kind: ServiceAccount
    name: "{{ include "acc-common.serviceAccountName" . }}"
