apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-netconf-init-config-job-reader"
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
    resourceNames:
      - "{{ .Release.Name }}-netconf-init-config"
