apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orancontroller-clusterrolebinding
  namespace: accelleran
subjects:  
- kind: ServiceAccount
  name: orancontroller
  namespace: default
roleRef:  
  kind: ClusterRole
  name: orancontroller-clusterrole
  apiGroup: rbac.authorization.k8s.io
