apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orancontroller-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - deletecollection
  - patch
  - update
