apiVersion: v1
kind: ConfigMap
metadata:
 name: conf-l3-yaml
 labels:
   {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  l3-template.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: l3-bootstrap-%s # LOW_INSTANCE_ID
      labels:
        app: l3-pod
        ncss: l3-%s # LOW_INSTANCE_ID
    data:
      l3.bootstrap: |
        redis.hostname:{{ tpl .Values.config.redis.hostname . }}
        redis.port:{{ .Values.config.redis.port }}
        instance.filter:%s # INSTANCE_ID
    ---
    apiVersion: v1
    kind: Pod
    metadata: 
      name: l3-%s # LOW_INSTANCE_ID
      labels: 
        app: l3-pod
        ncss: l3-%s # LOW_INSTANCE_ID
    spec: 
      containers:
        - name: l3-container
          image: accelleran/drax-l3-%s:{{ tpl .Values.config.l3Version . }} # DUPLEX
          volumeMounts:
            - mountPath: /data/l3.bootstrap
              name: l3-bootstrap-%s # LOW_INSTANCE_ID
              subPath: "l3.bootstrap"
          securityContext:
            privileged: true
      volumes:
        - name: l3-bootstrap-%s # LOW_INSTANCE_ID
          configMap:
            name: l3-bootstrap-%s # LOW_INSTANCE_ID
      imagePullSecrets:
        - name: accelleran-secret



