apiVersion: v1
kind: ConfigMap
metadata:
 name: conf-l3-del-all-url
 labels:
   {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  l3-delete-all_url: |
    <!orchestratorUrl!>/api/v1/namespaces/<!lowNamespace!>/pods?labelSelector=app=l3-pod
    <!orchestratorUrl!>/api/v1/namespaces/<!lowNamespace!>/configmaps?labelSelector=app=l3-pod
    <!orchestratorUrl!>/api/v1/namespaces/<!lowNamespace!>/services?labelSelector=app=l3-pod
