apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oran-clustercontrol.fullname" . }}
  labels:
    {{- include "oran-clustercontrol.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oran-clustercontrol.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oran-clustercontrol.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.config.https }}
      serviceAccountName: {{ include "oran-clustercontrol.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.version . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVED_NAMESPACE
              value: "{{ tpl .Values.config.l3Namespace . }}"
#          command: ["sudo"]
#          args: ["/data/oran/ocstart"]
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
#            - name: acc-oran
#              mountPath: /data
            - name: bootstrap-config
              mountPath: /data/oc.bootstrap
              subPath: "oc.bootstrap"
            - name: conf-l3-yaml
              mountPath: /data/l3-template.yaml
              subPath: "l3-template.yaml"
            - name: conf-zlog
              mountPath: /data/zlog.conf
              subPath: "zlog.conf" 
#            - name: l3-tdd-start-config
#              mountPath: /data/l3-tdd/l3start
#              subPath: "l3start"
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.service.port }}
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
#        - name: acc-oran
#          {{- if .Values.persistence.enabled }}
#          persistentVolumeClaim:
#            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "oran-clustercontrol.fullname" . }}{{- end }}
#          {{- end }}
        - name: bootstrap-config
          configMap:
            name: bootstrap-config
        - name: conf-l3-yaml
          configMap:
            name: conf-l3-yaml
        - name: conf-zlog
          configMap:
            name: conf-zlog
#        - name: l3-fdd-start-config
#          configMap:
#            name: l3-fdd-start-config  
