apiVersion: v1
kind: Service
metadata:
  name: {{ include "oran-clustercontrol.fullname" . }}
  labels:
    {{- include "oran-clustercontrol.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "oran-clustercontrol.selectorLabels" . | nindent 4 }}
