{{- if .Values.config.https -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oran-clustercontrol.serviceAccountName" . }}
  labels:
    {{- include "oran-clustercontrol.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
