apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "configurator.fullname" . }}
  labels:
    {{- include "configurator.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "configurator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "configurator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "configurator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-provisioner
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.provisioner.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              /bin/sh <<'EOF'
              until curl -k https://{{ .Values.provisioner.provisionerApi }}:{{ .Values.provisioner.provisionerPort }}/get/; do sleep 5; done
              curl --cacert /certs/ca.crt --cert /certs/client.crt --key /certs/client.key https://{{ .Values.provisioner.provisionerApi }}:{{ .Values.provisioner.provisionerPort }}/push/ --data-binary @/config/cellconfig.yaml
              EOF
          volumeMounts:
            - name: prov-ca-crt
              mountPath: /certs/ca.crt
              subPath: "ca.crt"
            - name: prov-client-key
              mountPath: /certs/client.key
              subPath: "client.key"
            - name: prov-client-crt
              mountPath: /certs/client.crt
              subPath: "client.crt"
            - name: cell-config
              mountPath: /config/cellconfig.yaml
              subPath: "cellconfig.yaml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: prov-ca-crt
          configMap:
            name: {{ .Values.provisioner.caCrtName }}
        - name: prov-client-key
          configMap:
            name: {{ .Values.provisioner.clientKeyName }}
        - name: prov-client-crt
          configMap:
            name: {{ .Values.provisioner.clientCrtName }}
        - name: cell-config
          configMap:
            name: cell-config
