apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oran-clustercontrol.fullname" . }}-4g-netconf-config
  labels:
    {{- include "oran-clustercontrol.labels" . | nindent 4 }}
data:
  4grc-netconf-config.py: |
    from netconf_client.connect import connect_ssh
    from netconf_client.ncclient import Manager
    import time

    HOST = "{{ .Values.jobs.netconfConfig.netconfHost }}"
    PORT = 830

    session = connect_ssh(host=HOST, port=PORT, username="helm", password="helm")
        mgr = Manager(session, timeout=120)
        models = """
                  <enb-internal xmlns="http://accelleran.com/ns/yang/accelleran-enb-internal" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
                  	<feature-flags xc:operation="create">
                  		<handout-enabled>true</handout-enabled>
                  		<handin-enabled>true</handin-enabled>
                  		<son-enabled>false</son-enabled>
                  		<cbrs-enabled>false</cbrs-enabled>
                  		<snmp-enabled>false</snmp-enabled>
                  		<imsi-sniffing-enabled>false</imsi-sniffing-enabled>
                  		<mme-slicing-enabled>false</mme-slicing-enabled>
                  		<ran-slicing-enabled>false</ran-slicing-enabled>
                  		<reestablish-enabled>false</reestablish-enabled>
                  		<erab-add-enabled>true</erab-add-enabled>
                  		<erab-remove-enabled>removeERAB</erab-remove-enabled>
                  		<channel-dimensioning-enabled>false</channel-dimensioning-enabled>
                  		<mocn-enabled>false</mocn-enabled>
                  		<remote-management-type>netconf</remote-management-type>
                  	</feature-flags>

                  	<socket-interface>eth0</socket-interface>

                  	<common xc:operation="create">
                  		<logging xc:operation="create"><id>frm-common</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-datastore</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-fsm</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-list</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-memory</id><severity>error</severity></logging>
                  		<logging xc:operation="create"><id>frm-message</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-posix</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>frm-queue</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-schedule</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-socket</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>frm-sysutil</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-timer</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-io</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-http</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>frm-string</id><severity>error</severity></logging>
                  		<logging xc:operation="create"><id>frm-pubsub</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-snmp</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-tasks</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-health-monitor</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-system-monitor</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>frm-watchdog</id><severity>warning</severity></logging>

                  		<logging xc:operation="create"><id>appl-stacks</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-main</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-http</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-remmgmt</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-platform</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-proxy</id><severity>warning</severity></logging>
                  		<logging xc:operation="create"><id>appl-lifecycle-mgmt</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-oran</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-netconf</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-beacon</id><severity>info</severity></logging>
                  		<logging xc:operation="create"><id>appl-data-distribution</id><severity>info</severity></logging>
                  	</common>

                  	<ric-controller-config xc:operation="create">
                  	 	<automatic-handover>true</automatic-handover>
                  	 	<publish-measurement-data>true</publish-measurement-data>
                  	 	<publish-ue-data>true</publish-ue-data>
                  	 	<measurement-type>periodic</measurement-type>
                  	 	<orchestrator-url>http://10.55.2.2:8080</orchestrator-url>
                  	</ric-controller-config>


                  </enb-internal>

                """

        print(mgr.edit_config(config=models,target='running', default_operation=None))
