{{- if .Values.config.natsKafkaTopics.override }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "golang-nkafka.fullname" . }}-kafkatopics
data:
  KafkaTopics.toml: |-
    [options]
    default_kafka_topic="{{ .Values.config.natsKafkaTopics.defaultKafkaTopic }}"

    {{- range $translations := .Values.config.natsKafkaTopics.translations }}
    [[translate]]
    nats_subject="{{ .natsSubject }}"
    kafka_topic="{{ .kafkaTopic }}"
    {{- end }}
{{- end }}
